apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::456742808460:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-16KYNSML7VVZZ
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::456742808460:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2022-11-13T10:14:36Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1597"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: f2fd50c9-6bac-4e51-9408-c87882d1e5aa
